import fs from "node:fs";import path from "node:path";
const root=process.cwd(),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8"));
const required=["date","headline","summary","regime","markets","drivers","sources"];
const idx=read("data/daily/index.json");
for(const date of idx.dates){const d=read(`data/daily/${date}.json`);for(const key of required)if(!(key in d))throw Error(`${date}: missing ${key}`);if(d.date!==date)throw Error(`${date}: date mismatch`);if(!fs.existsSync(path.join(root,`reports/${date}.md`)))throw Error(`${date}: missing Markdown report`)}
const latest=read("data/daily/latest.json");if(latest.date!==idx.latest)throw Error("latest.json and index.json disagree");
const stocks=read("data/stocks/index.json"),must=["AAPL","GOOGL","MSFT","0700.HK","9992.HK"];for(const t of must)if(!stocks.some(s=>s.ticker===t))throw Error(`missing core stock ${t}`);
const memory=read("data/memory/latest.json"),reads=read("data/reads/latest.json");
for(const key of ["asOf","instrument","signals","map","indexView","watch","risks"])if(!(key in memory))throw Error(`memory: missing ${key}`);
if(!memory.instrument.url)throw Error("memory: missing fund URL");
if(!Array.isArray(reads.items)||!reads.items.every(x=>x.url&&x.title&&x.summary))throw Error("reads: invalid item");
const briefBase="data/ai-briefings/",briefIdx=read(briefBase+"index.json"),bilingual=v=>v&&typeof v.zh==="string"&&v.zh.trim()&&typeof v.en==="string"&&v.en.trim();
if(briefIdx.schemaVersion!==2||!Array.isArray(briefIdx.dates)||!briefIdx.dates.length||new Set(briefIdx.dates).size!==briefIdx.dates.length||briefIdx.latest!==briefIdx.dates[0])throw Error("Invalid AI briefing index");
for(const date of briefIdx.dates){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error("Invalid AI briefing date");const b=read(briefBase+date+".json"),needed=["schemaVersion","date","kind","asOf","readingMinutes","headline","summary","items","radar","tryToday","coverage","executive"];for(const key of needed)if(!(key in b))throw Error(`${date}: briefing missing ${key}`);if(b.schemaVersion!==2||b.date!==date||!Number.isFinite(Date.parse(b.asOf))||!Number.isInteger(b.readingMinutes)||b.readingMinutes<8||b.readingMinutes>15)throw Error(`${date}: invalid briefing metadata`);for(const key of ["headline","summary"])if(!bilingual(b[key]))throw Error(`${date}: missing bilingual ${key}`);for(const key of ["signal","watch"])if(!bilingual(b.executive[key]))throw Error(`${date}: missing bilingual executive ${key}`);if(!Array.isArray(b.items)||b.items.length<4||!Array.isArray(b.radar)||b.radar.length<3||!Array.isArray(b.tryToday)||b.tryToday.length<1)throw Error(`${date}: insufficient briefing coverage`);for(const item of b.items){for(const key of ["category","title","what","why","implication"])if(!bilingual(item[key]))throw Error(`${date}: item missing bilingual ${key}`);if(!["confirmed","context","background","analysis"].includes(item.status)||!Array.isArray(item.sources)||!item.sources.length)throw Error(`${date}: invalid briefing item`);for(const source of item.sources){const url=new URL(source.url);if(url.protocol!=="https:"||!source.label||!["primary","news","analysis"].includes(source.type))throw Error(`${date}: invalid briefing source`)}if(item.status==="confirmed"&&!item.sources.some(source=>source.type==="primary"))throw Error(`${date}: confirmed item lacks primary source`)}for(const item of b.radar){for(const key of ["category","title","summary"])if(!bilingual(item[key]))throw Error(`${date}: radar missing bilingual ${key}`);if(!["confirmed","analysis"].includes(item.status)||!Array.isArray(item.sources)||!item.sources.length)throw Error(`${date}: invalid radar item`)}for(const step of b.tryToday)if(!bilingual(step))throw Error(`${date}: missing bilingual action`);if(!fs.existsSync(path.join(root,`reports/ai-briefings/${date}.md`)))throw Error(`${date}: missing briefing Markdown`);if(b.kind==="daily"){const start=Date.parse(b.coverage?.windowStart),end=Date.parse(b.coverage?.windowEnd),asOf=Date.parse(b.asOf);if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end||end>asOf||!b.items.some(item=>item.status==="confirmed"))throw Error(`${date}: invalid daily coverage or evidence`)}}
const briefLatest=read(briefBase+"latest.json");if(briefLatest.schemaVersion!==2||briefLatest.date!==briefIdx.latest)throw Error("AI briefing latest pointer mismatch");
console.log(`Validated ${idx.dates.length} reports, ${stocks.length} stocks, memory research, ${reads.items.length} reading links and ${briefIdx.dates.length} AI briefing(s).`);
